/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SignupResult {
  accountId: number;
  profileId: number;
  role: string | null;
}

export interface SignupResponse {
  accessToken: string;
  refreshToken: string;
  result: SignupResult;
};
