/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EnumRoles = "admin" | "user";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  createdAt: Generated<Timestamp | null>;
  email: string | null;
  id: Generated<Int8>;
  password: string;
  phone: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface AccountRole {
  accountId: Int8;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  roleId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface CronJob {
  active: Generated<boolean>;
  command: string;
  database: Generated<string>;
  jobid: Generated<Int8>;
  jobname: string | null;
  nodename: Generated<string>;
  nodeport: Generated<number>;
  schedule: string;
  username: Generated<string>;
}

export interface CronJobRunDetails {
  command: string | null;
  database: string | null;
  endTime: Timestamp | null;
  jobid: Int8 | null;
  jobPid: number | null;
  returnMessage: string | null;
  runid: Generated<Int8>;
  startTime: Timestamp | null;
  status: string | null;
  username: string | null;
}

export interface KyselySeeds {
  name: string;
  timestamp: Generated<Timestamp>;
}

export interface Role {
  id: Generated<Int8>;
  name: EnumRoles;
}

export interface UserPermission {
  createdAt: Generated<Timestamp | null>;
  id: Generated<Int8>;
  updatedAt: Generated<Timestamp | null>;
  userId: Int8;
}

export interface Users {
  accountId: Int8;
  createdAt: Generated<Timestamp | null>;
  externalId: string | null;
  firstName: string;
  id: Generated<Int8>;
  lastName: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  account: Account;
  accountRole: AccountRole;
  "cron.job": CronJob;
  "cron.jobRunDetails": CronJobRunDetails;
  kyselySeeds: KyselySeeds;
  users: Users;
}
