CREATE EXTENSION IF NOT EXISTS pg_cron;
GRANT USAGE ON SCHEMA cron TO postgres;

-- Types
CREATE TYPE enum_roles AS ENUM (
  'admin',
  'user'
);

-- Tables
CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  external_id TEXT, -- for SSO integration
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE account (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(255) UNIQUE DEFAULT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_permission (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name enum_roles NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS account_role (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--

-- Insert default roles
INSERT INTO role (name) VALUES ('admin') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('user') ON CONFLICT DO NOTHING;
--


-- Foreign Key Constraints
ALTER TABLE account_role ADD CONSTRAINT fk_account_role_account FOREIGN KEY (account_id) REFERENCES account(id)
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE account_role ADD CONSTRAINT fk_account_role_role FOREIGN KEY (role_id) REFERENCES role(id)
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE users ADD CONSTRAINT fk_users_account FOREIGN KEY (account_id) REFERENCES account(id)
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE user_permission ADD CONSTRAINT fk_user_permission_user FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;
